variables:
- name: resource-group
  value: tue-100-automation-central
- name: automation-account
  value: ir75wgbevjpqg
- name: location
  value: eastus
- name: config-location
  value: 'config/iis.ps1'

trigger:
  branches:
    include:
    - main
  # paths:
  #   include:
  #     - /solutions/azure-hub-spoke/*
  #   exclude:
  #     - '/solutions/azure-hub-spoke/README.md'
  #     - '/solutions/azure-hub-spoke/bicep/*'

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'ls'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
    ScriptType: 'InlineScript'
    Inline: 'Import-AzAutomationDscConfiguration -AutomationAccountName $(automation-account) -ResourceGroupName $(resource-group) -SourcePath $(config-location) -Force -Published'
    azurePowerShellVersion: 'LatestVersion'

