variables:
- name: resource-group
  value: kv-001
- name: automation-account
  value: phsovkb7zgqho
- name: location
  value: eastus
- name: config-name
  value: iis
- name: config-location
  value: config/iis.ps1

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - config/*

pool:
  vmImage: windows-2019

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
    KeyVaultName: 'aphsovkb7zgqhob'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: Install AzureSignTool

- task: CmdLine@2
  displayName: 'Sign outputted .exe with global AzureSignTool'
  inputs:
    script: AzureSignTool sign -kvu "$(SigningVaultURL)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" --azure-key-vault-tenant-id "$(SigningTenantId)" -kvc 'dsc-poc-self-signed' -v $(config-location)

# - task: AzurePowerShell@5
#   inputs:
#     azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
#     ScriptType: 'InlineScript'
#     Inline: 'Import-AzAutomationDscConfiguration -AutomationAccountName $(automation-account) -ResourceGroupName $(resource-group) -SourcePath $(config-location) -Force -Published'
#     azurePowerShellVersion: 'LatestVersion'
#   displayName: Import Configuration

# - task: AzurePowerShell@5
#   inputs:
#     azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
#     ScriptType: 'InlineScript'
#     azurePowerShellVersion: 'LatestVersion'
#     Inline: |
#       $Params = @{"DomainName"="contoso.com";"DNSAddress"="10.0.2.4"}
#       Start-AzAutomationDscCompilationJob -ConfigurationName $(config-name) -Parameters $Params -AutomationAccountName $(automation-account) -ResourceGroupName $(resource-group)
#   displayName: Compile Configuration
    