variables:
- name: resource-group
  value: tue-100-automation-central
- name: automation-account
  value: ir75wgbevjpqg
- name: location
  value: eastus
- name: config-name
  value: iis
- name: config-location
  value: config/iis.ps1

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - '/config/*''

pool:
  vmImage: ubuntu-latest

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
    ScriptType: 'InlineScript'
    Inline: 'Import-AzAutomationDscConfiguration -AutomationAccountName $(automation-account) -ResourceGroupName $(resource-group) -SourcePath $(config-location) -Force -Published'
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ca-nepeters-demo-test(3762d87c-ddb8-425f-b2fc-29e5e859edaf)'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      $Params = @{"DomainName"="contoso.com";DNSAddress"="10.0.2.4"}
      Start-AzAutomationDscCompilationJob -ConfigurationName $(config-name) -Parameters $Params -AutomationAccountName $(automation-account) -ResourceGroupName $(resource-group)
    