name: Build ARM Tempalte

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Install Bicep build
        run: |
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help

      - name: Run Bicep build
        run: |
            # echo "-------"
            # ls
            # cd master
            # ls
            # echo "-------"
            bicep build master/deploy/main.bicep
            ls -l master/deploy/*.json
          
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: Update Bicep-ARM template
          add: master/deploy/main.json